### ISSUE TITLE
Have patterns instead of just filenames

### ISSUE THREAD

**Issue by pascallouisperez** [helloeave/lidder#2]
Would be nice to allow a whole directory for instance

```
rules:
  - do not print, instead log:
    pattern: fmt\.Print
    expected:
      # these are fine
      - cmd/.*
```
